[localk8s]
k8s-master1.local
k8s-file1.local
k8s-database1.local
k8s-worker[1:3].local

[masters]
k8s-master1.local

[fileservers]
k8s-file1.local

[databases]
k8s-database1.local

[workers]
k8s-worker[1:2].local
