---
- name: Common Configuration
  hosts: "*"
  vars:
    dnscrypt_listen_address: "127.0.2.1"
    dnscrypt_listen_port: 53
    ssh_public_keys:
      - comment: "Home Desktop Public Key"
        key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDPUOa0+zQzDOCCHDOB++XHIFpOmkoIknABMeInPV83MMJwnu+aSaB6fIlmSmdva6ivCKflM45DfdB6JhHNDMJc/E5HP7qpE9M3g9PD3XbuafBDbpCHysfJC9p1QMxMBzlX8RiUC+g6u1S8WLV4vdjEYTwDldr34C/fuk+43FOSXvG0DoxiGik5KAEwdoZsy+IcTxhL0bZF7YlePh8Mhx8ABMylvgfpas2PRtwbs0LCWH+7sqMLH+H+kZnnSUxP7MsDrhMXiPPgW5SFZe1lPrrV+t0o9bk3KKArS7IN46fcUoV6Gkf7MdZCkAiXCfOWe4ONjH/A1b2pT0DAgGnp/GLN"
      - comment: "Laptop Public Key"
        key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC9+LhmchErX29/bRWessCTwDW2hPdwW31y4d8MDJudQZd0xJqY+womSj3uSVzIEnFTY+a4HKWKnH1bAO1wtIDurELG5qPorsVbPG/1Imw+3KJVkVYml5q1K9MCmFtrzNO18r8I5KN6/BgZcjMmherFtYF681R7d7MLw4o1Zt5+5OXVE5CIeJjtoC+x7/PN1baGnFEudh8rns/JQaWz4zvU87hf3QNWRvhaA87XlQ01fkRyar5wIHv6lPz5FpiyTpkVAPiT0zaGTWw3Iu2cxsT0sqBIXDOPDNcjegiUjLMvTUuGkIShR6/rdlOBNsiHVNtUIxggvTUKPypa+0XhGxWflhy3vh/dby1q9HPJUTu0LPBugSOMhLFBiLVzUkFgRoalzeMgVjE8gE5Fvyv+2xpVVu6qGF23IXhxNFeKUrwfcUyI44YLDRWc4Am82lHs8W4ABq6J327tCpzi2WdYW1sdzZzTjh3CInr2R+gMvXxoj54X1UefjuKLehBr2bBIAM+U5ZI/CZf6NS1svF8S8hdUzVYqr4bRMmrhy5o+VL6eJUeSsYDYHlqc7ilIrRUV1qvpSvL7bAyfbKrO1TlHRRy/MYoVJj7DR2HCJVsWraIJI7L0swUiH75qAFN0F3f9hSwQviyk1hlPkA1XElKCjn4As2SV8e3pvGiYUrVyC7hasw== jonathan@wilbur.space"
  tasks:
    - name: Set Timezone
      timezone:
        name: America/New_York
    - name: Configure OpenSSH
      ansible.builtin.copy:
        content: "{{ lookup('file', 'configuration/sshd_config') }}"
        dest: /etc/ssh/sshd_config
    - name: Install SSH Public Keys
      authorized_key:
        user: ubuntu
        key: "{{ item.key }}"
        comment : "{{ item.comment }}"
        path: /home/ubuntu/.ssh/authorized_keys
        state: present
      loop: "{{ ssh_public_keys }}"
    - name: Enable SSH Daemon
      ansible.builtin.systemd:
        name: ssh
        enabled: yes
        state: restarted
    - name: Install secure-delete APT Package
      apt:
        name: secure-delete
        update_cache: yes
        state: latest
    - name: Install hexyl APT Package
      apt:
        name: hexyl
        update_cache: yes
        state: latest
    - name: Install avahi-daemon APT Package
      apt:
        name: avahi-daemon
        update_cache: yes
        state: latest
    - name: Get the NordVPN Repository Debian File
      ansible.builtin.get_url:
        url: https://repo.nordvpn.com/deb/nordvpn/debian/pool/main/nordvpn-release_1.0.0_all.deb
        dest: /tmp/nordvpn.deb
      ignore_errors: yes # This fails sometimes, but unless it fails the first time, it is not a problem.
    - name: Install NordVPN Repository from the Debian File
      ansible.builtin.apt:
        deb: /tmp/nordvpn.deb
    - name: Install NordVPN
      apt:
        name: nordvpn
        update_cache: yes
        state: present
    - name: Make sure dnsmasq is not installed
      apt:
        name: dnsmasq
        state: absent
    - name: Install DNSCrypt Proxy
      apt:
        name: dnscrypt-proxy
        update_cache: yes
        state: present
    # Source: https://github.com/Ultimate-Hosts-Blacklist/Ultimate.Hosts.Blacklist
    - name: Download the Hosts Blacklist
      ansible.builtin.get_url:
        url: https://hosts.ubuntu101.co.za/domains.list
        dest: /etc/dnscrypt-proxy/dns.blacklist
    - name: Block metrics.ubuntu.com
      ansible.builtin.lineinfile:
        dest: /etc/dnscrypt-proxy/dns.blacklist
        line: "metrics.ubuntu.com"
        state: present
    - name: Block popcon.ubuntu.com
      ansible.builtin.lineinfile:
        dest: /etc/dnscrypt-proxy/dns.blacklist
        line: "popcon.ubuntu.com"
        state: present
    - name: Configure DNSCrypt Proxy
      ansible.builtin.copy:
        content: "{{ lookup('file', 'configuration/dnscrypt-proxy.toml') }}"
        dest: /etc/dnscrypt-proxy/dnscrypt-proxy.toml
    - name: Configure Systemd to use DNSCrypt Proxy
      ansible.builtin.copy:
        content: "{{ lookup('file', 'configuration/resolved.conf') }}"
        dest: /etc/systemd/resolved.conf
    # I cannot seem to configure my router to support this anyway.
    # - name: Enable Ethernet Jumbo Frames
    #   ansible.builtin.lineinfile:
    #     dest: /etc/dhcpcd.conf
    #     regexp: '^(\s*)option interface-mtu'
    #     line: '\1option interface-mtu 9000;'
    #     state: present
    #     backrefs: yes
    - name: Enable and Restart DNSCrypt Proxy Daemon
      ansible.builtin.systemd:
        name: dnscrypt-proxy
        enabled: yes
        state: restarted
    - name: Enable and Restart SystemD-Resolved
      ansible.builtin.systemd:
        name: systemd-resolved
        enabled: yes
        state: restarted
    # Source: https://askubuntu.com/questions/1027532/how-to-opt-out-of-system-information-reports
    - name: Purge ubuntu-report
      apt:
        name: ubuntu-report
        purge: yes
        state: absent
    - name: Purge popularity-contest
      apt:
        name: popularity-contest
        purge: yes
        state: absent
    - name: Purge apport
      apt:
        name: apport
        purge: yes
        state: absent
    - name: Purge whoopsie
      apt:
        name: whoopsie
        purge: yes
        state: absent
    - name: Ensure ASLR
      sysctl:
        name: kernel.randomize_va_space
        value: "1"
    # Not valid on all systems.
    # - name: Ensure ExecShield
    #   sysctl:
    #     name: kernel.exec-shield
    #     value: "1"
    - name: Disable IP Forwarding
      sysctl:
        name: net.ipv4.ip_forward
        value: "0"
    - name: Periodically delete command history
      ansible.builtin.cron:
        name: Delete command history
        job: "rm /home/ubuntu/.bash_history"
        special_time: weekly
        state: present
    - name: Automatically logout users
      ansible.builtin.lineinfile:
        dest: /etc/profile
        regexp: '^(\s*)TMOUT='
        line: '\1TMOUT=1200'
        state: present
        backrefs: yes

- name: Storage Server Configuration
  hosts: stores
  vars:
    stores:
      - device: /dev/sda
        fs: xfs
        mount: /mnt/store01
      - device: /dev/sdb
        fs: xfs
        mount: /mnt/store02
  tasks:
    - name: Install mdadm APT Package
      apt:
        name: mdadm
        update_cache: yes
        state: latest
    - name: "Create USB Drive Partition {{ store.device }}1"
      parted:
        device: "{{ item.device }}"
        number: 1
        state: present
        fs_type: "{{ item.fs }}"
      loop: "{{ stores }}"
    - name: "Format USB Drive Partition {{ store.device }}1 as XFS"
      filesystem:
        fstype: "{{ item.fs }}"
        dev: "{{ item.device }}1"
      loop: "{{ stores }}"
    - name: "Auto-Mount USB Drive Partition {{ store.device }} 1"
      mount:
        path: "{{ item.mount }}"
        src: "{{ item.device }}1"
        fstype: "{{ item.fs }}"
        state: present
      loop: "{{ stores }}"
    - name: Periodically zero freed storage
      ansible.builtin.cron:
        name: "Zero Freed Storage on {{ item.mount }}"
        job: "sfill -lf {{ item.mount }}"
        special_time: monthly
        state: present
      loop: "{{ stores }}"


- name: Kubernetes Common Configuration
  hosts: localk8s
  tasks:
    - name: Enable cgroups
      ansible.builtin.lineinfile:
        dest: /boot/firmware/cmdline.txt
        regexp: '^(.*)(?<!cgroup_enable=memory cgroup_memory=1)$'
        line: '\1 cgroup_enable=memory cgroup_memory=1'
        state: present
        backrefs: yes
    - name: Install microk8s snap
      snap:
        name: microk8s
        classic: yes
        state: present
    - name: Wait until microK8s is running
      shell: microk8s status --wait-ready
    - name: Enable DNS
      shell: microk8s enable dns
    - name: Enable Dashboard
      shell: microk8s enable dashboard
    - name: Enable Registry
      shell: microk8s enable registry
    - name: Enable Helm 3
      shell: microk8s enable helm3
    - name: Get all namespaces
      shell: microk8s kubectl get all --all-namespaces
    - name: Set File Descriptor Limits for Microk8s
      ansible.builtin.lineinfile:
        dest: /var/snap/microk8s/current/args/containerd-env
        line: "ulimit -n 65536"
        state: present
