apiVersion: v1
kind: PersistentVolume
metadata:
  name: database-sda1-pv
spec:
  capacity:
    storage: 235G
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  # We use "Retain" because this is critical data
  # persistentVolumeReclaimPolicy: Delete
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /data/sda1
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k8s-database1