apiVersion: v1
kind: Service
metadata:
  name: gitea
spec:
  type: NodePort
  selector:
    app: gitea
  ports:
  - port: 3000
    targetPort: 80
    protocol: TCP
  - port: 222
    targetPort: 22
    protocol: TCP
