apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: slow
  namespace: storage
provisioner: kubernetes.io/glusterfs
parameters:
  resturl: "http://k8s-file1.home:8080"
  clusterid: "481a3091cc0243430adbfa64ddd5fbc7"
  restauthenabled: "true"
  restuser: "admin"
  secretNamespace: "default"
  secretName: "heketi-secret"
  gidMin: "40000"
  gidMax: "50000"
  volumetype: "replicate:3"