apiVersion: apps/v1
kind: Deployment
metadata:
  name: glusterfs-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: glusterfs-server
  template:
    metadata:
      labels:
        app: glusterfs-server
    spec:
      nodeSelector:
        role: fileserver
      containers:
      - name: glusterfs-server
        image: gluster-centos
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
