apiVersion: v1
kind: Secret
metadata:
  name: heketi-secret
  namespace: storage
data:
  # Not much of a secret anymore!
  # Still, this is expected to be deployed on private networks, so this should not be a problem.
  key: bUFxbzFBNFI0cWxFWGdNWQ==
type: kubernetes.io/glusterfs