apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: glusterfs
  namespace: storage
provisioner: kubernetes.io/glusterfs
allowVolumeExpansion: true
parameters:
  resturl: "http://k8s-file1.local:8080"
  clusterid: "6a02135daea544004220961189b9efac"
  restuser: "admin"
  secretNamespace: "storage"
  secretName: "heketi-secret"
  volumetype: none