apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: glusterfs
  namespace: storage
provisioner: kubernetes.io/glusterfs
allowVolumeExpansion: true
parameters:
  resturl: "http://k8s-file1.home"
  clusterid: "481a3091cc0243430adbfa64ddd5fbc7"
  restuser: "admin"
  secretNamespace: "storage"
  secretName: "heketi-secret"
  volumetype: "replicate:1"