kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: glusterfs-test-pvc
  labels:
    app: glusterfs-test
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi
  storageClassName: glusterfs